-- ClientCheck: Supabase schema and seed.
-- Generated by scripts/generate-seed-sql.mjs. Do not edit by hand.
--
-- Paste into the SQL editor of project kufvqlqkmqnacicnritb, then set
-- VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env and restart the dev
-- server. The app will switch from "Fallback data" to "Supabase data" on its
-- own and Settings will report every table as readable.

create table if not exists public.accounts (
  id                      text primary key,
  name                    text not null,
  industry                text not null,
  health_score            integer not null,
  status                  text not null,
  risk_factors            text[] default '{}',
  fleet_size              integer not null default 0,
  flight_hours_last_30d   integer not null default 0,
  uptime_pct              numeric(5,2) not null default 0,
  open_tickets            integer not null default 0,
  csat                    integer not null default 0,
  arr                     bigint not null default 0,
  renewal_date            date,
  last_qbr_date           date,
  csm_initials            text
);

create table if not exists public.tickets (
  id          text primary key,
  account_id  text not null references public.accounts(id) on delete cascade,
  subject     text not null,
  priority    text not null,
  age_days    integer not null default 0,
  sla_state   text not null
);

create table if not exists public.churned_accounts (
  id          text primary key,
  name        text not null,
  industry    text not null,
  churn_date  date,
  arr_lost    bigint not null default 0,
  reason      text
);

create table if not exists public.churn_rate_monthly (
  month           text primary key,
  churn_rate_pct  numeric(5,2) not null default 0,
  accounts_lost   integer not null default 0,
  arr_lost        bigint not null default 0
);

create table if not exists public.account_meta (
  account_id             text primary key references public.accounts(id) on delete cascade,
  ae_initials            text,
  ai_inbox_enabled       boolean not null default false,
  billing_status         text,
  plan                   text,
  period_end             date,
  wallet_balance_usd     bigint not null default 0,
  usage_tier             text,
  contract_start         date,
  website                text,
  slack_channel          text,
  automation_success_kit boolean not null default false,
  multi_year             boolean not null default false,
  last_mbr_date          date,
  next_mbr_date          date,
  next_qbr_date          date,
  exclude_from_metrics   boolean not null default false,
  churn_reason           text,
  operational_status     text,
  seats                  integer not null default 0,
  csm_health_score       integer,
  region                 text
);

-- Row level security is on for every table. The frontend only ever holds the
-- publishable anon key, so read access is granted explicitly and nothing else.
-- Grant write access only if you want the in-app edits to persist, and scope it
-- to authenticated users rather than anon in anything beyond a prototype.
alter table public.accounts           enable row level security;
alter table public.tickets            enable row level security;
alter table public.churned_accounts   enable row level security;
alter table public.churn_rate_monthly enable row level security;
alter table public.account_meta       enable row level security;

do $$
declare t text;
begin
  foreach t in array array['accounts','tickets','churned_accounts','churn_rate_monthly','account_meta']
  loop
    execute format('drop policy if exists anon_read on public.%I', t);
    execute format('create policy anon_read on public.%I for select to anon using (true)', t);
  end loop;
end $$;

insert into public.accounts (id, name, industry, health_score, status, risk_factors, fleet_size, flight_hours_last_30d, uptime_pct, open_tickets, csat, arr, renewal_date, last_qbr_date, csm_initials) values
  ('ACC-1042', 'Meridian Mining Co.', 'Mining', 62, 'Watch', '{"Declining flight hours","Ticket volume spike","No QBR in 90+ days"}', 34, 412, 96.4, 4, 68, 480000, '2026-10-02', '2026-04-18', 'AV'),
  ('ACC-1043', 'Coastal Port Authority', 'Maritime Ports', 54, 'At Risk', '{"CSAT below threshold","Uptime drop","Renewal approaching with low health"}', 22, 286, 94.1, 3, 61, 620000, '2026-09-04', '2026-03-05', 'DM'),
  ('ACC-1049', 'Granite Ridge Utilities', 'Electric Utilities', 79, 'Healthy', '{}', 61, 1240, 98.6, 0, 84, 940000, '2027-01-31', '2026-07-09', 'SR'),
  ('ACC-1051', 'Northstar Solar Systems', 'Solar', 88, 'Healthy', '{}', 48, 903, 99.2, 0, 92, 355000, '2027-02-14', '2026-06-22', 'AV'),
  ('ACC-1055', 'Harborline Security', 'Security Services', 44, 'At Risk', '{"Ticket volume spike","CSAT below threshold","Declining flight hours"}', 17, 148, 92.8, 3, 52, 210000, '2026-10-18', '2026-01-22', 'AV'),
  ('ACC-1060', 'Apex Rail Operations', 'Railroad Operations', 71, 'Watch', '{"No QBR in 90+ days","Uptime drop"}', 39, 602, 97.1, 1, 76, 715000, '2027-03-20', '2026-02-27', 'KT'),
  ('ACC-1063', 'Cascade Petrochem', 'Oil & Gas', 91, 'Healthy', '{}', 76, 1580, 99.5, 0, 94, 1250000, '2027-06-30', '2026-07-31', 'SR'),
  ('ACC-1067', 'Ironwood Data Centers', 'Data Centers', 83, 'Healthy', '{}', 12, 224, 99.1, 0, 89, 168000, '2027-04-15', '2026-06-11', 'DM'),
  ('ACC-1071', 'Fairview Public Safety Bureau', 'Public Safety', 66, 'Watch', '{"Renewal approaching with low health","CSAT below threshold"}', 28, 470, 97.8, 1, 70, 395000, '2026-10-15', '2026-05-14', 'KT'),
  ('ACC-1074', 'Bedrock Construction Group', 'Construction', 58, 'Watch', '{"Declining flight hours","No QBR in 90+ days"}', 25, 197, 96.9, 1, 72, 265000, '2026-12-12', '2026-01-30', 'AV'),
  ('ACC-1078', 'Longhaul Freight Systems', 'Transportation', 76, 'Healthy', '{}', 44, 810, 98.2, 0, 81, 520000, '2027-05-22', '2026-07-17', 'DM'),
  ('ACC-1082', 'Silverline Copper Works', 'Mining', 49, 'At Risk', '{"Uptime drop","Ticket volume spike","Renewal approaching with low health"}', 31, 268, 93.4, 2, 58, 430000, '2026-11-30', '2026-02-11', 'SR'),
  ('ACC-1086', 'Beacon Bay Terminals', 'Maritime Ports', 73, 'Watch', '{"No QBR in 90+ days"}', 19, 356, 98, 0, 79, 305000, '2027-07-31', '2026-03-28', 'KT'),
  ('ACC-1090', 'Redstone Grid Partners', 'Electric Utilities', 85, 'Healthy', '{}', 53, 1105, 98.9, 0, 87, 680000, '2027-08-14', '2026-08-05', 'AV')
on conflict do nothing;

insert into public.account_meta (account_id, ae_initials, ai_inbox_enabled, billing_status, plan, period_end, wallet_balance_usd, usage_tier, contract_start, website, slack_channel, automation_success_kit, multi_year, last_mbr_date, next_mbr_date, next_qbr_date, exclude_from_metrics, churn_reason, operational_status, seats, region) values
  ('ACC-1042', 'PJ', true, 'Current', 'Fleet Advanced', '2026-10-02', 12400, 'Over', '2023-10-03', 'meridianmining.example', '#acct-meridian-mining', true, true, '2026-07-24', '2026-08-28', '2026-09-11', false, '', 'Watch', 18, 'North America'),
  ('ACC-1043', 'PJ', true, 'Past Due', 'Fleet Enterprise', '2026-09-04', 0, 'On Plan', '2022-10-01', 'coastalportauthority.example', '#acct-coastal-port', false, true, '2026-07-16', '2026-08-27', '2026-09-04', false, '', 'At Risk', 26, 'North America'),
  ('ACC-1049', 'HN', true, 'Current', 'Fleet Enterprise', '2027-01-31', 48000, 'On Plan', '2024-02-01', 'graniteridgeutilities.example', '#acct-granite-ridge', true, true, '2026-08-06', '2026-09-03', '2026-10-08', false, '', 'Healthy', 34, 'North America'),
  ('ACC-1051', 'HN', true, 'Current', 'Fleet Advanced', '2027-02-14', 21500, 'On Plan', '2024-02-15', 'northstarsolarsystems.example', '#acct-northstar-solar', true, false, '2026-08-11', '2026-09-08', '2026-09-25', false, '', 'Healthy', 22, 'North America'),
  ('ACC-1055', 'TB', false, 'In Collections', 'Fleet Standard', '2026-10-18', 0, 'Under', '2024-10-19', 'harborlinesecurity.example', '#acct-harborline', false, false, '2026-06-12', '2026-08-26', '2026-09-02', false, '', 'At Risk', 9, 'North America'),
  ('ACC-1060', 'TB', true, 'Current', 'Fleet Enterprise', '2027-03-20', 33000, 'On Plan', '2023-03-21', 'apexrailoperations.example', '#acct-apex-rail', true, true, '2026-07-30', '2026-09-02', '2026-09-18', false, '', 'Watch', 28, 'North America'),
  ('ACC-1063', 'PJ', true, 'Prepaid', 'Fleet Enterprise', '2027-06-30', 96000, 'Over', '2022-07-01', 'cascadepetrochem.example', '#acct-cascade-petrochem', true, true, '2026-08-13', '2026-09-10', '2026-10-29', false, '', 'Healthy', 41, 'North America'),
  ('ACC-1067', 'HN', false, 'Current', 'Fleet Standard', '2027-04-15', 7200, 'Under', '2025-04-16', 'ironwooddatacenters.example', '#acct-ironwood-dc', false, false, '2026-08-04', '2026-09-01', '2026-09-24', false, '', 'Healthy', 6, 'EMEA'),
  ('ACC-1071', 'TB', true, 'Current', 'Fleet Advanced', '2026-10-15', 5400, 'On Plan', '2023-10-16', 'fairviewpsb.example', '#acct-fairview-psb', true, true, '2026-07-21', '2026-08-25', '2026-09-09', false, '', 'Watch', 16, 'North America'),
  ('ACC-1074', 'PJ', false, 'Current', 'Fleet Standard', '2026-12-12', 3100, 'Under', '2024-12-13', 'bedrockconstruction.example', '#acct-bedrock', false, false, '2026-06-26', '2026-08-31', '2026-09-16', false, '', 'Watch', 11, 'North America'),
  ('ACC-1078', 'HN', true, 'Current', 'Fleet Advanced', '2027-05-22', 18900, 'On Plan', '2023-05-23', 'longhaulfreight.example', '#acct-longhaul', true, true, '2026-08-07', '2026-09-04', '2026-10-15', false, '', 'Healthy', 24, 'North America'),
  ('ACC-1082', 'TB', true, 'Past Due', 'Fleet Advanced', '2026-11-30', 0, 'Under', '2023-12-01', 'silverlinecopper.example', '#acct-silverline', false, true, '2026-07-09', '2026-08-27', '2026-09-08', false, '', 'At Risk', 15, 'LATAM'),
  ('ACC-1086', 'PJ', false, 'Current', 'Fleet Standard', '2027-07-31', 9600, 'On Plan', '2025-08-01', 'beaconbayterminals.example', '#acct-beacon-bay', true, false, '2026-07-28', '2026-09-01', '2026-09-29', false, '', 'Watch', 8, 'APAC'),
  ('ACC-1090', 'HN', true, 'Current', 'Fleet Enterprise', '2027-08-14', 41000, 'On Plan', '2024-08-15', 'redstonegrid.example', '#acct-redstone-grid', true, true, '2026-08-05', '2026-09-02', '2026-11-05', false, '', 'Healthy', 31, 'North America')
on conflict do nothing;

insert into public.tickets (id, account_id, subject, priority, age_days, sla_state) values
  ('TCK-4102', 'ACC-1042', 'Dock 3 charging station fails handshake after firmware 4.2', 'Urgent', 9, 'Breached'),
  ('TCK-4104', 'ACC-1043', 'RTK base station loses fix during shift change', 'Urgent', 12, 'Breached'),
  ('TCK-4106', 'ACC-1055', 'Night patrol docking failure in high wind', 'High', 11, 'Breached'),
  ('TCK-4108', 'ACC-1042', 'Thermal payload calibration drift on two airframes', 'High', 6, 'At Risk'),
  ('TCK-4111', 'ACC-1082', 'Dust ingress warning on dock 1 after pit blast', 'High', 8, 'At Risk'),
  ('TCK-4115', 'ACC-1042', 'Scheduled mission skips waypoint 7 intermittently', 'Medium', 4, 'On Track'),
  ('TCK-4117', 'ACC-1071', 'Live stream latency above 4s for command vehicle', 'High', 6, 'At Risk'),
  ('TCK-4119', 'ACC-1043', 'Perimeter geofence alerts not reaching duty phone', 'High', 7, 'At Risk'),
  ('TCK-4121', 'ACC-1055', 'Video retention policy not applied to archived missions', 'Medium', 5, 'At Risk'),
  ('TCK-4124', 'ACC-1074', 'Site boundary import rejects DXF from surveyor', 'Medium', 4, 'On Track'),
  ('TCK-4127', 'ACC-1043', 'Operator roles reset after SSO directory sync', 'Medium', 3, 'On Track'),
  ('TCK-4129', 'ACC-1082', 'Stockpile volume report differs from survey crew', 'Medium', 3, 'On Track'),
  ('TCK-4133', 'ACC-1060', 'Track inspection mission fails pre-flight compass check', 'Medium', 2, 'On Track'),
  ('TCK-4136', 'ACC-1055', 'Add second operator seat to shift schedule', 'Low', 1, 'On Track'),
  ('TCK-4131', 'ACC-1042', 'Export of flight logs times out beyond a 30 day range', 'Low', 2, 'On Track')
on conflict do nothing;

insert into public.churned_accounts (id, name, industry, churn_date, arr_lost, reason) values
  ('CHU-0912', 'Foothill Aggregates', 'Mining', '2026-07-31', 185000, 'Consolidated to a competing platform'),
  ('CHU-0908', 'Tidewater Marine Terminal', 'Maritime Ports', '2026-05-15', 240000, 'Site decommissioned'),
  ('CHU-0903', 'Sable Creek Energy', 'Oil & Gas', '2026-03-31', 310000, 'Budget reduction after asset sale'),
  ('CHU-0900', 'Northgate Quarry', 'Construction', '2026-02-27', 128000, 'Consolidated to a competing platform'),
  ('CHU-0897', 'Copperline Transit', 'Transportation', '2026-01-31', 145000, 'Program ended after pilot phase'),
  ('CHU-0891', 'Vantage Yard Services', 'Security Services', '2025-11-30', 96000, 'Moved to a managed service provider'),
  ('CHU-0885', 'Pinnacle Grid Works', 'Electric Utilities', '2025-09-30', 275000, 'Moved to in-house flight operations')
on conflict do nothing;

insert into public.churn_rate_monthly (month, churn_rate_pct, accounts_lost, arr_lost) values
  ('2025-09', 3.1, 1, 275000),
  ('2025-10', 0, 0, 0),
  ('2025-11', 1.1, 1, 96000),
  ('2025-12', 0, 0, 0),
  ('2026-01', 1.7, 1, 145000),
  ('2026-02', 1.5, 1, 128000),
  ('2026-03', 3.8, 1, 310000),
  ('2026-04', 0, 0, 0),
  ('2026-05', 3, 1, 240000),
  ('2026-06', 0, 0, 0),
  ('2026-07', 2.4, 1, 185000),
  ('2026-08', 0, 0, 0)
on conflict do nothing;

